server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
