openapi: 3.0.1
info:
  title: Card creation API
  version: 1.0.0
servers:
  - url: https://api.something.com/v1

paths:
  /api/v1/card-request:
    post:
      operationId: createCard
      tags:
        - new-card-request
      summary: Create new card
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/NewCardRequest'
        required: true
      responses:
        201:
          description: New card request successfully created.
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/card-request/{oib}:
    get:
      operationId: getCard
      tags:
        - new-card-request
      summary: Returns card for a given user oib.
      parameters:
        - in: path
          required: true
          name: oib
          schema:
            type: string
      responses:
        200:
          description: User card.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardResponse'
        404:
          description: Card not found.
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      operationId: deleteCard
      tags:
        - new-card-request
      summary: Delete card for a given oib.
      parameters:
        - in: path
          required: true
          name: oib
          schema:
            type: string
      responses:
        204:
          description: Card deleted successfully.
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    NewCardRequest:
      title: Card request
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        status:
          type: string
        oib:
          type: string
    CardResponse:
      title: Card response
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        status:
          type: string
        oib:
          type: string
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Optional error code for reporting purposes
        id:
          type: string
          description: Unique identifier for audit purposes
        description:
          type: string
          description: The description of the error
    Response:
      title: Response
      type: object
      properties:
        message:
          type: string