CREATE TABLE credit_card
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
    oib        VARCHAR(11)  UNIQUE NOT NULL,
    first_name VARCHAR(50)  NOT NULL,
    last_name  VARCHAR(50)  NOT NULL,
    status     VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP
);

INSERT INTO credit_card (oib, first_name, last_name, status, created_at)
VALUES ('12345678901', 'Test', 'User', 'PENDING', CURRENT_TIMESTAMP()),
('00312312311', 'Ivan', 'Ivic', 'APPROVED', CURRENT_TIMESTAMP()),
('75267198210', 'Pero', 'Peric', 'REJECTED', CURRENT_TIMESTAMP());

